### ISSUE TITLE
undefined method `width'

### ISSUE THREAD

**Issue by tashmays** [middagj/quirc-ruby#1]
When trying to use Quirc in my test suite I keep getting an error stating "undefined method `width'"
![Screen Shot 2019-06-14 at 11 37 48 AM](https://user-images.githubusercontent.com/15879721/59527479-e8989e00-8e98-11e9-9a4f-f5f7346c18e9.png)

I have tried not QR coded images and still receive the same error. Not sure what I am doing wrong. Hopefully you can point me in the right direction. Thank you

**Comment by middagj** [comment]
You have to specify a binary string or [ChunkyPNG](http://chunkypng.com/) image instead of a path. If you specify a binary string, the `width` and `height` arguments are required and called on the `image` argument. You are passing a String, which does not have the method `width` and fails.

I have added an [example](https://github.com/middagj/quirc-ruby#example) to put you and others in the right direction how to use this library.

**Comment by tashmays** [comment]
Thank you for getting back to me. I have some additional questions. I have required gem 'chunky_png' and verified that it is working. 
I have used your example like so:
`img` = `ChunkyPNG::Image.from_file('tmp/qrcode.png')`

am returned this data:

![Screen Shot 2019-06-17 at 9 33 32 AM](https://user-images.githubusercontent.com/15879721/59617219-2a1c8980-90e3-11e9-9f11-4583cbd2030c.png)

When I try decoding the image I get back `nil`:

![Screen Shot 2019-06-17 at 9 35 29 AM](https://user-images.githubusercontent.com/15879721/59617317-5932fb00-90e3-11e9-8a93-aba9767668dd.png)

I have also tried decoding the image like so:

![Screen Shot 2019-06-17 at 9 38 05 AM](https://user-images.githubusercontent.com/15879721/59617535-bf1f8280-90e3-11e9-9f08-7d2d96b8e636.png)

![Screen Shot 2019-06-17 at 9 38 25 AM](https://user-images.githubusercontent.com/15879721/59617565-ccd50800-90e3-11e9-8eda-92f19be3ec9b.png)

I have verified that the QR image does work with an authenticator and able to decode the image. Is there something I am missing. Thank you again.

**Comment by middagj** [comment]
Both methods are correct, if you get nil, it means that the decoder couldn't find any QR codes in your image. The `decode` method returns an array with all the found QR images. Taking the first of an empty array gives you zero. 

From your result it looks like your image doesn't have white space around the QR code. That is necessary. This gem is based on a C library [Quirc](https://github.com/dlbeer/quirc). Your authenticator app could use a different library. If you could share an example I can take a look.
