### ISSUE TITLE
quirc.c:51:5: error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by bbozo** [middagj/quirc-ruby#2]
I'd be happy to try and fix this myself - I just need a pointer where to plug this in :-)

```
current directory: /opt/InfoSwitch/Gateway/vendor/bundle/ruby/2.6.0/gems/quirc-0.1.1/ext/quirc
make "DESTDIR="
compiling quirc.c
quirc.c: In function ‘decoder_m_decode’:
quirc.c:51:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < num_codes; i++) {
     ^
quirc.c:51:5: note: use option -std=c99 or -std=gnu99 to compile your code
quirc.c: At top level:
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]
make: *** [quirc.o] Error 1

make failed, exit code 2
```

**Comment by middagj** [comment]
Seems you have a C compiler that defaults to C89, which is strange because in Rakefile I have added CFLAGS='-std=c99'. Which OS are you on? What is your `cc -v` output?

**Comment by bbozo** [comment]
> Seems you have a C compiler that defaults to C89, which is strange because in Rakefile I have added CFLAGS='-std=c99'. Which OS are you on? What is your `cc -v` output?

Yeah, it's weird also because I added `-std=gnu99` in the Makefile :smile: (https://github.com/info-sig/quirc-ruby/pull/1) - but with no luck :smile: the option just doesn't end up in the `Makefile` in the build directory

It's on CentOS 7:

```
$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
```

**Comment by middagj** [comment]
It seems that the cflags only apply to the C files using ExtensionTask, which is only the glue quirc.c. It does not work to the Makefile in the lib folder. Basic idea was to keep that as much similar to the original library, but because I don't expect anyone to have that library installed at their system, I just embedded it in the gem.

I have updated the repo with the additional option and bumped the version. Could you try if that works?

**Comment by bbozo** [comment]
It's a funny one - when I check out the git repo, go into `ext/quirc/embed` and run `make` - it works,

when I create a `Gemfile` and do `bundle` - it fails

**Comment by middagj** [comment]
And if you remove tmp folder?

**Comment by bbozo** [comment]
> And if you remove tmp folder?

Hmm, tmp folder?

**Comment by middagj** [comment]
Ruby caches intermediate compile results in the tmp directory of the gem (this repo).

**Comment by ddhamnekar** [comment]
@middagj : I used the latest version 0.1.2, but still faced the same issue. Would be helpful if you could declare the variable outside the for loop. Your views?

**Comment by middagj** [comment]
Declaring the variable outside the loop would fix this problem, but I like to use C99, although Centos 7 is old, it isn't that old, so it should be possible.

I used a Centos 7 docker image to see if I could locate the problem. It seems that when installing a gem from Rubygems, it doens't use the extra flags in the Rakefile (which in hindsight is obvious), contrary to using `rake compile` from source. I changed the code to set the `--std=c99` in the `extconf.rb` and publish it as 0.1.3. This version I could install with `gem install quirc` on a Centos 7 docker image with Ruby 2.6.0.

Could you try it?

**Comment by middagj** [comment]
I assume this issue is fixed. If not feel free to reopen.
